server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/paymentdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: PAYMENT-SERVICE

  config:
    import: configserver:http://localhost:9296
